name: Publish Nuget package

on:
  release:
    types: [published]
    
jobs:
  build-test-pack:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Pack
      run: dotnet pack ./DPBlazorMapLibrary/DPBlazorMapLibrary.csproj --output nupkgs --no-build --configuration Release -p:PackageVersion=${{ github.event.release.tag_name }}

    - name: Rename pack
      run: |
        cd ./nupkgs
        mv DPBlazorMapLibrary.${{ github.event.release.tag_name }}.nupkg GenOne.DPBlazorMap.${{ github.event.release.tag_name }}.nupkg
      
    - name: Push
      run: dotnet nuget push ./nupkgs/GenOne.DPBlazorMap.${{ github.event.release.tag_name }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
